version: '3'
services:
  vyos01:
    image: 2stacks/vyos:latest
    command: /sbin/init
    volumes:
    - /lib/modules:/lib/modules
    privileged: true
    networks:
      mgmt_nw:
        ipv4_address: 10.0.0.3
      client_nw:
        ipv4_address: 172.31.1.254
      server_nw:
        ipv4_address: 172.31.2.254

  vyos02:
    image: 2stacks/vyos:latest
    command: /sbin/init
    volumes:
    - /lib/modules:/lib/modules
    privileged: true
    networks:
      mgmt_nw:
        ipv4_address: 10.0.0.4
      client_nw:
        ipv4_address: 172.31.1.253
      server_nw:
        ipv4_address: 172.31.2.253
      
  Server:
    build:
      context: .
    image: centos:centos7
    volumes:
    - ./ansible_practice:/ansible_practice
    networks:
      mgmt_nw:
        ipv4_address: 10.0.0.5
      server_nw:
        ipv4_address: 172.31.2.2
        
  Client:
    build:
      context: .
    image: centos:centos7
    volumes:
    - ./ansible_practice:/ansible_practice
    networks:
      mgmt_nw:
        ipv4_address: 10.0.0.6
      client_nw:
        ipv4_address: 172.31.1.2
        
  ansible:
    build:
      context: .
    image: ansible
    volumes:
    - ./ansible_practice:/ansible_practice
    networks:
      mgmt_nw:
        ipv4_address: 10.0.0.2

networks:
  mgmt_nw:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  
  client_nw:
    ipam:
      driver: default
      config:
        - subnet: 172.31.1.0/24

  server_nw:
    ipam:
      driver: default
      config:
        - subnet: 172.31.2.0/24
