version: '3'
services:
  vyos01:
    image: higebu/vyos:latest
    command: /sbin/init
    volumes:
    - /lib/modules:/lib/modules
    privileged: true
    networks:
      network1:
        ipv4_address: 10.0.0.3
        
  vyos02:
    image: higebu/vyos:latest
    command: /sbin/init
    volumes:
    - /lib/modules:/lib/modules
    privileged: true
    networks:
      network1:
        ipv4_address: 10.0.0.4

  Server:
    build:
      context: .
    image: centos:centos7
    volumes:
    - ./ansible_practice:/ansible_practice
    networks:
      network1:
        ipv4_address: 10.0.0.5
        
  Client:
    build:
      context: .
    image: centos:centos7
    volumes:
    - ./ansible_practice:/ansible_practice
    networks:
      network1:
        ipv4_address: 10.0.0.6
        
  ansible:
    build:
      context: .
    image: ansible
    volumes:
    - ./ansible_practice:/ansible_practice
    networks:
      network1:
        ipv4_address: 10.0.0.2

networks:
  default:
    external:
      name: bridge
  container-link:
    name: network1
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"

networks:
  default:
    external:
      name: bridge
  container-link:
    name: network2
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.31.1.0/24"
  
networks:
  default:
    external:
      name: bridge
  container-link:
    name: network2
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.31.2.0/24"
